### PR TITLE
Merge fd-1D-sphere into develop

### PR DESCRIPTION
**Pull request by rouson**
This PR incorporates the stand-alone 1D spherical heat equation solver into the FD framework.

### CODE REVIEW

**Comment by porteri** [comment]
@rouson @zbeekman FYI this does not build on Windows w/ Intel. It hits an ICE in the file `src/FD/grid/spherical_1D_conductor_implementation`

**Comment by rouson** [comment]
Thanks, @porteri. I’ll see if I can reproduce the ICE.

**Comment by rouson** [comment]
@porteri  I am able to reproduce the ICE with the Intel 18 compiler on Linux.  I'll develop a workaround.

**Comment by rouson** [comment]
@porteri I fixed the ICE with the Intel compiler and eliminated several warnings related to entities with long names.  All `fd` tests pass for me.  If you can confirm that the same is true for you with the Intel compiler on Windows, then I'll merge this.

**Pull request merged**
